name: TryHackMe Badge Workflow

permissions:
  contents: write  # Required for pushing changes

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Ensure assets directory exists
        run: mkdir -p ./assets

      - name: Debug Environment Variables
        run: |
          echo "GITHUB_TOKEN is set: ${GITHUB_TOKEN:+Yes}"
          echo "Checking image_path exists: ./assets/thm_propic.png"
          ls ./assets || echo "Directory is empty!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run TryHackMe Badge Workflow
        uses: p4p1/tryhackme-badge-workflow@1.0.0
        with:
          image_path: ./assets/thm_propic.png
          username: Slavetomints
          committer_username: thm-p4p1-bot
          committer_email: p4p1@thm.bot
          commit_message: Updated TryHackMe Badge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug Git Status
        run: |
          echo "Git status:"
          git status
          echo "Testing push permissions..."
          git push origin main || echo "Failed to push!"
