name: TryHackMe Badge Workflow

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Create assets directory if it doesn't exist
        run: mkdir -p ./assets  # This ensures the 'assets' directory exists

      - name: Run TryHackMe Badge Workflow
        uses: p4p1/tryhackme-badge-workflow@1.0.0
        with:
          image_path: ./assets/thm_propic.png  # Relative path from repository root
          username: Slavetomints  # Replace with your TryHackMe username
          committer_username: thm-p4p1-bot
          committer_email: p4p1@thm.bot
          commit_message: Updated TryHackMe Badge
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
